Add GPU support for model and flows
tonyduan/normalizing-flows pull request #6
Opened 2020-04-22 09:28 UTC by Baukebrenninkmeijer

I added GPU support for all forward/inverse passes. The tensors are moved to the same device as the input tensor (so wherever x or z are). For now, the result of sampling will be moved to the CPU, since I expect that to most often be the use-case. Let me know if you have any other suggestions.

2020-04-22 18:12 UTC, tonyduan commented
This looks great thanks for adding GPU support. I've left some comments on the PR.

2020-04-22 18:12 UTC, tonyduan requested changes
This looks great thanks for adding GPU support. I've left some comments on the PR.

2020-04-22 18:12 UTC, tonyduan commented on nf/models.py
> +        return x.to('cpu')
Don't think sending to CPU here is necessary. We can let the samples stay on the same device as `self.prior`.

2020-04-22 18:12 UTC, tonyduan commented on nf/flows.py
> +        z = torch.zeros_like(x).to(x.device)
`torch.zeros_like` should already match the device of its input. 

So no need for `.to(x.device)` on all lines that use `torch.zeros_like`

2020-04-22 18:12 UTC, tonyduan commented on nf/flows.py
> +        log_det = torch.zeros(z.shape[0]).to(x.device)
I believe it's more idiomatic to replace these types of lines with 

`log_det = torch.zeros(z.shape[0], device=x.device)`

2020-04-23 12:56 UTC, Baukebrenninkmeijer commented
Moves device location to tensor initialization instead of after. Removed the cpu as default location for sampling, and is now taking the same location as the prior. Should be good now :).

2020-04-23 13:52 UTC, Baukebrenninkmeijer commented
The parameters in OneByOneConv are not registered correctly as parameters, and are not moved to the correct device when we call model.to(device). So now i'm calling the `.to` in the forward and backward call individually.

2020-04-23 19:31 UTC, tonyduan commented
Thanks for making the requested changes.

> The parameters in OneByOneConv are not registered correctly as parameters, and are not moved to the correct device when we call model.to(device). So now i'm calling the .to in the forward and backward call individually.

I think we can fix this by replacing the line:

`self.P = torch.tensor(P, dtype = torch.float)`

with:

`self.P = nn.Parameter(torch.tensor(P, dtype = torch.float), requires_grad = False)`

Could you take a stab at this and let me know if this fixes the issue?

2020-04-28 12:14 UTC, Baukebrenninkmeijer commented
Yes, i'll have a look when I have time. Hopefully, somewhere later this week.

2024-09-24 11:57 UTC, closed without merging